### ISSUE TITLE
Final Sprint

### ISSUE THREAD

**Issue by vivianknee** [vivianknee/vivianblog#8]
# Tasks
- [ ] Integrate leaderboard for cyber house to the overall leaderboard (50% done)
- [ ] Create a key system to better integrate cyber games with fight game
- If a user plays a certain number of cyber games --> keys are unlocked on the home page map that can be collected --> these keys can give the users character powerups to use in the fights (skip a question, get a hint, etc) 

# Skills
- [ ] javascript and Java to do backend and frontend for leaderboard
- [ ] use tiles more to do the keys on the map
- [ ] allowing users to use powerups will likely be frontend, additional code to files that already exist
